name: Test

on: [pull_request_target]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
	  echo ${{ github.event.pull_request.head.ref }}
