on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TEST: ${{github.head_ref}}
    steps:
        - run: |
            echo ${{github.repository}}
            echo ${{github.head_ref}}
            echo $TEST
            echo "$TEST"
            $TEST
            "$TEST"
